# Parameters related to building rocblas
ARG base_image

FROM ${base_image}
LABEL maintainer="hipblas-maintainer@amd.com"

ARG user_uid

ARG library_dependencies="rocblas rocsolver"

# Install dependent packages
RUN yum install -y --nogpgcheck\
    sudo \
    centos-release-scl \
    devtoolset-7 \
    ca-certificates \
    git \
    cmake3 \
    make \
    clang \
    clang-devel \
    gcc-c++ \
    gcc-gfortran \
    gtest-devel \ 
    gtest \
    pkgconfig \
    python27 \
    python36 \
    python36-devel \
    python36-pip \
    python36-pytest \
    python36-setuptools \
    PyYAML \
    libcxx-devel \
    boost-devel \
    numactl-libs \
    rpm-build \ 
    deltarpm \
    wget \
    unzip \
    ${library_dependencies} 

RUN echo '#!/bin/bash' | tee /etc/profile.d/devtoolset7.sh && echo \
    'source scl_source enable devtoolset-7' >>/etc/profile.d/devtoolset7.sh

RUN pip3 install wheel && pip3 install tox pyyaml
    
# docker pipeline runs containers with particular uid
# create a jenkins user with this specific uid so it can use sudo priviledges
# Grant any member of sudo group password-less sudo privileges
RUN useradd --create-home -u ${user_uid} -o -G video --shell /bin/bash jenkins && \
    echo '%video ALL=(ALL) NOPASSWD:ALL' | tee /etc/sudoers.d/sudo-nopasswd && \
    chmod 400 /etc/sudoers.d/sudo-nopasswd
