# Parameters related to building hip
ARG base_image

FROM ${base_image}
LABEL maintainer="hipblas-maintainer@amd.com"

ARG user_uid
ARG library_dependencies="rocblas rocsolver"

# Install dependent packages
# Dependencies:
# * hcc-config.cmake: pkg-config
# * tensile: python2.7, python-yaml
# * hipblas-test: gfortran, googletest
# * hipblas-bench: libboost-program-options-dev
# * libhsakmt.so: libnuma1
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    sudo \
    ca-certificates \
    git \
    make \
    cmake \
    pkg-config \
    python2.7 \
    python-yaml \
    gfortran \
    libboost-program-options-dev \
    libnuma1 \
    libomp-dev \
    wget \
    unzip \
    ${library_dependencies} \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# docker pipeline runs containers with particular uid
# create a jenkins user with this specific uid so it can use sudo priviledges
# Grant any member of sudo group password-less sudo privileges
RUN useradd --create-home -u ${user_uid} -o -G video --shell /bin/bash jenkins && \
    mkdir -p /etc/sudoers.d/ && \
    echo '%video   ALL=(ALL) NOPASSWD:ALL' | tee /etc/sudoers.d/sudo-nopasswd
