# Parameters related to building hipblas
ARG base_image

FROM ${base_image}
LABEL maintainer="hipblas-maintainer@amd.com"

# Copy the rpm package of hipblas into the container from host
COPY *.rpm /tmp/

# Install the rpm package, and print out contents of expected changed locations
RUN yum -y update && yum install -y\
    /tmp/hipblas-*.rpm \
  && rm -f /tmp/*.rpm \
  && yum -y clean all \
  && rm -rf /var/lib/apt/lists/* \
  && printf "ls -la /etc/ld.so.conf.d/\n" && ls -la /etc/ld.so.conf.d/ \
  && printf "ls -la /opt/rocm/include\n" && ls -la /opt/rocm/include \
  && printf "ls -la /opt/rocm/lib\n" && ls -la /opt/rocm/lib \
  && printf "ls -la /opt/rocm/lib/cmake\n" && ls -la /opt/rocm/lib/cmake \
  && printf "ls -la /opt/rocm/hipblas/include\n" && ls -la /opt/rocm/hipblas/include \
  && printf "ls -la /opt/rocm/hipblas/lib\n" && ls -la /opt/rocm/hipblas/lib
