FROM ubuntu:16.04
MAINTAINER Kent Knox <kent.knox@amd>

# Parameters related to building hipblas
ARG REPO_RADEON=repo.radeon.com

# Initialize the image we are working with
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y curl && \
    curl -sL http://$REPO_RADEON/rocm/apt/debian/rocm.gpg.key | apt-key add - && \
    echo 'deb [arch=amd64] http://$REPO_RADEON/rocm/apt/debian/ xenial main' | tee /etc/apt/sources.list.d/rocm.list && \
    apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    rocm-dev \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Copy the debian package of hcc-lc into the container from host
COPY *.deb /tmp/

# Install the debian package, and print out contents of expected changed locations
RUN dpkg -i /tmp/*.deb && \
    rm -f /tmp/*.deb && \
    printf "cat /etc/ld.so.conf.d/hipblas-dev.conf\n" && cat /etc/ld.so.conf.d/hipblas-dev.conf && \
    printf "ls -la /opt/rocm/include\n" && ls -la /opt/rocm/include && \
    printf "ls -la /opt/rocm/lib \n" && ls -la /opt/rocm/lib && \
    printf "ls -la /opt/rocm/lib/cmake\n" && ls -la /opt/rocm/lib/cmake && \
    printf "ls -la /opt/rocm/hipblas/include\n" && ls -la /opt/rocm/hipblas/include && \
    printf "ls -la /opt/rocm/hipblas/lib\n" && ls -la /opt/rocm/hipblas/lib
