# Parameters related to building rocblas
ARG base_image

FROM ${base_image}
LABEL maintainer="kent.knox@amd"

# Copy the debian package of rocblas into the container from host
COPY *.deb /tmp/

# Install the debian package, and print out contents of expected changed locations
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends --allow-unauthenticated -y \
        /tmp/hipblas-*.deb \
    && rm -f /tmp/*.deb \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && printf "cat /etc/ld.so.conf.d/hipblas-dev.conf\n" && cat /etc/ld.so.conf.d/hipblas-dev.conf \
    && printf "ls -la /opt/rocm/include\n" && ls -la /opt/rocm/include \
    && printf "ls -la /opt/rocm/lib\n" && ls -la /opt/rocm/lib \
    && printf "ls -la /opt/rocm/lib/cmake\n" && ls -la /opt/rocm/lib/cmake \
    && printf "ls -la /opt/rocm/hipblas/include\n" && ls -la /opt/rocm/hipblas/include \
    && printf "ls -la /opt/rocm/hipblas/lib\n" && ls -la /opt/rocm/hipblas/lib
